/**
 * Offline fallback.
 *
 * When the API cannot be reached, the dashboard serves this bundled snapshot
 * instead of showing an error. Two reasons it exists:
 *
 *  1. The static deployment is useful before the backend is hosted at all.
 *  2. It is the demo's safety net — a dead venue network no longer means a dead
 *     demo.
 *
 * The UI always states when it is running on the fallback, so it can never be
 * mistaken for live satellite data.
 *
 * Generated by `scripts/generate_fallback.py`. Do not hand-edit the JSON.
 */

import type { Analytics, Filters, Hotspot, HotspotCollection, ThermalClass } from "../types";
import raw from "./snapshot.json";

/** Snapshot records carry an age offset instead of an absolute timestamp. */
type SnapshotRecord = Omit<Hotspot, "acquired_at"> & { hours_ago: number };

/** Rebuild timestamps at load so the bundled demo always reads as recent. */
function hydrate(): Hotspot[] {
  const now = Date.now();
  return (raw as SnapshotRecord[]).map(({ hours_ago, ...rest }) => ({
    ...rest,
    acquired_at: new Date(now - hours_ago * 3_600_000).toISOString(),
  }));
}

/** Mirrors the server-side filtering in `backend/app/main.py`. */
export function fallbackHotspots(filters: Filters): HotspotCollection {
  let results = hydrate();

  if (filters.predictedClass !== "all") {
    results = results.filter(
      (h) => h.classification?.predicted_class === filters.predictedClass,
    );
  }
  if (filters.minConfidence > 0) {
    results = results.filter(
      (h) => (h.classification?.confidence ?? 0) >= filters.minConfidence,
    );
  }
  if (filters.withinHours !== "all") {
    const cutoff = Date.now() - filters.withinHours * 3_600_000;
    results = results.filter((h) => Date.parse(h.acquired_at) >= cutoff);
  }

  results.sort((a, b) => Date.parse(b.acquired_at) - Date.parse(a.acquired_at));
  return { count: results.length, hotspots: results, data_source: "sample" };
}

export function fallbackAnalytics(): Analytics {
  const all = hydrate();

  const byClass = {
    industrial_fire: 0,
    persistent_industrial: 0,
    natural_fire: 0,
    unknown: 0,
  } satisfies Record<ThermalClass, number>;

  for (const hotspot of all) {
    const cls = hotspot.classification?.predicted_class;
    if (cls) byClass[cls] += 1;
  }

  const alerts = all.filter(
    (h) =>
      h.classification?.predicted_class === "industrial_fire" &&
      h.classification.confidence >= 0.7,
  ).length;

  return {
    total_hotspots: all.length,
    by_class: byClass,
    alerts,
    data_source: "sample",
  };
}
